### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [JonathanReeve/chapterize#9]
Hi,
Amazing project!
I'm interested in using Chapterize as a Python library, and was wondering if it might be possible to switch the license so not all upstream projects have to be GPL as well. Would you consider switching the license to a more permissive one such as MIT, ISC, etc?
Thank you!

**Comment by JonathanReeve** [comment]
Hi mrfakename, I chose the GPL license because it guarantees software freedom to my project and to upstream projects, as well. This is important to me, because I want users of my software to have the freedom to download the code, inspect it, modify it, and so on, regardless of what other project that code appears in. I suggest that you license your project with the GPL, as well, which will ensure that upstream projects are also GPL-licensed. That would be a very good thing for everyone involved, since users of all these projects would benefit from these freedoms, as well.
